logo: logo.jpg # add logo name
title: Registered Sex Perverters List
description:  # this means to ignore newlines until "baseurl:"
  This is the global sex perverter's registry.
  A sex perverter is an individual who perverts the justice system in the case of laws against sex crimes.
  We are now in a time where asdfsafsa. This is a radicalist belief and it is scary that it is not being viewed as such. When radicalist Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
url: ''

# Banner settings
video: # add banner video. Add your video file to the folder video
banner-title: Registered Sex Perverters List # add banner title
banner-desc: This is the global sex perverter's registry. # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
